# NOTE: secrets are mounted in the container at /run/secrets/<secret_name>

name: transcendence

services:
# # ========================= CERT GEN CHECK ========================
#     caddy-cert-check:
#         container_name: caddy-cert-check
#         build:
#             context: ./caddy-cert-check-service
#             dockerfile: Dockerfile
#         expose:
#             - "443"

# ========================= CADDY ========================
    caddy:
        container_name: caddy
        build:
            context: ./caddy-service
            dockerfile: Dockerfile
        ports:
            - "8443:443"
            - "8080:80"
        networks:
            - transcendence-network
        volumes:
            - caddy-volume:/data/caddy/
        develop:
            watch:
              - action: sync+exec
                path: ./caddy-service/
                target: /app
                ignore:
                    - .dockerfile
                    - Dockerfile
                exec:
                    command: "caddy reload"
        depends_on:
            frontend:
                condition: service_started
#            database-service:
#                condition: service_healthy
            auth-service:
                condition: service_started
#            chat-service:
#                condition: service_started
            # file-management-service:
            #     condition: service_started
            # kong-service:
            #     condition: service_started
#            user-management-service:
#                condition: service_started
        restart: always

# ======================== FRONT ========================
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            additional_contexts: 
                shared_ressources: ./shared
        expose:
            - "3000"
        develop:
            watch:
                - path: ./frontend
                  action: sync
                  target: /app
                  ignore:
                    - .git
                    - .dockerignore
                    - Dockerfile
        networks:
            - transcendence-network
        restart: unless-stopped

# ======================== AUTHENTICATION ========================
    auth-service:
        build:
            context: ./auth-service
            dockerfile: Dockerfile
            additional_contexts:
                shared_ressources: ./shared
        expose:
            - "3001"
        secrets:
            - api_pass
            - jwt_secret
            - github_oauth_id
            - github_oauth_secret
        develop:
            watch:
                - path: ./auth-service
                  action: sync
                  target: /app
                  ignore:
                    - .git
                    - .dockerignore
                    - Dockerfile
#        depends_on:
#            user-management-service:
#                condition: service_started
#                restart: true
#            database-service:
#                condition: service_healthy
#                restart: true
        restart: unless-stopped

# ======================== CHAT ========================
    chat-service:
        build:
            context: ./chat-service
            dockerfile: Dockerfile
            additional_contexts:
                shared_ressources: ./shared
        expose:
            - "3004"
        secrets:
            - api_pass
            - jwt_secret
            - github_oauth_id
            - github_oauth_secret
        develop:
            watch:
                - path: ./chat-service
                  action: sync
                  target: /app
                  ignore:
                    - .git
                    - .dockerignore
                    - Dockerfile
        depends_on:
            database-service:
                condition: service_healthy
                restart: true
            user-management-service:
                condition: service_started
                restart: true
            # tournament-service:
            #     condition: service_started
            #     restart: true
            # file-managment-service:
            #     condition: service_started
            #     restart: true
        restart: unless-stopped
        
# ======================== DB ========================
    database-service:
        container_name: database-service
        env_file: .env
        build:
            context: ./database-service
            dockerfile: Dockerfile
            additional_contexts: 
                shared_ressources: ./shared
        ports: # TEMPORARY
            - "5555:5555"  # ONLY TO CHECK DB FROM OUTSIDE, SO ONLY FOR DEV
        expose: 
            - "5000"
        environment:
            DATABASE_URL: ${DATABASE_URL}
            DB_USER: "user"
            DB_PASS_FILE: /run/secrets/db_password
            LAUNCH_MODE: "dev"
        secrets:
            - db_password
            - api_pass
        develop:
            watch:
                - path: ./database-service
                  action: sync+exec
                  target: /app
                  exec:
                    command: "./scripts/handle_file_change.sh {{ .Path }}"
                - path: shared/scripts
                  target: /app/scripts
                  action: sync
        volumes:
            - avatars-volume:/app/uploads
            - ./db_data:/app/data # ONLY FOR DEV
        networks:
            - transcendence-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"] #Probably need to put https in future
            interval: 10s
            timeout: 30s
            retries: 5
            start_period: 5s

# # ======================== FILE MANAGEMENT ========================
    # file-management-service:
    #     build:
    #         context: ./file-management-service
    #         dockerfile: Dockerfile
    #     expose: 
    #         - 5010
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #     restart: unless-stopped

# ======================== KONG ========================
#    kong-service:
#        build:
#            context: ./kong-service
#            dockerfile: Dockerfile
#        expose:
#            - "3000"
#        develop:
#            watch:
#                - path: ./**/*.tsx
#                  action: sync+exec
#                  target: /app
#                  exec:
#                    command: "./scripts/handle_file_change.sh {{ .Path }}"
#                - path: ../shared/scripts
#                  target: /app/scripts
#                  action: sync
#        restart: unless-stopped

# # ======================== TOURNAMENT ========================
    # tournament-service:
    #     build:
    #         context: ./tournament-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - "5003" 
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #         kong-service:
    #             condition: service_started
    #         rabbit-mq-service:
    #             condition: service_started
    #     restart: unless-stopped

# # ======================== TOURNAMENT ========================
    # rabbit-mq-service:
    #     build:
    #         context: ./rabbit-mq-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - "5000" 
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync

# ======================== USER MANAGEMENT ========================
    user-management-service:
        build:
            context: ./user-management-service
            dockerfile: Dockerfile
            additional_contexts:
                shared_ressources: ./shared
        expose:
            - "3003"
        secrets:
            - api_pass
        develop:
            watch:
                - path: ./**/*.tsx
                  action: sync+exec
                  target: /app
                  exec:
                    command: "./scripts/handle_file_change.sh {{ .Path }}"
                - path: ../shared/scripts
                  target: /app/scripts
                  action: sync
        depends_on:
            database-service:
                condition: service_healthy
                restart: true
        restart: unless-stopped

volumes:
    caddy-volume: 
    avatars-volume:

networks:
    transcendence-network:
        driver: bridge

secrets:
    github_oauth_id:
        file: secrets/github_oauth_id
    github_oauth_secret:
        file: secrets/github_oauth_secret
    api_pass:
        file: secrets/api_internal_key
    db_password:
        file: secrets/db_password
    jwt_secret:
        file: secrets/jwt_secret
    # db_url:
    #     environment: "DATABASE_URL" 

