# Add the develop options when I understand better what files to watch
# and my options here.
# develop:
#   watch:
#       - path: ./##
#         include: "#" #optional
#         ignore: "#.#" #optional
#         action: sync+exec
#         target: /##
#         exec:
#           command: ## ###
#
# NOTE: secrets are mounted in the container at /run/secrets/<secret_name>
#
# TODO determine specific ports and secret contents
# TODO put networks if I decide the default one is insufficient
# TODO grant access to secrets once I know better who needs what information
name: transcendence

services:
# ========================= CADDY ========================
    caddy:
        container_name: caddy
        build:
            context: ./caddy-service
            dockerfile: Dockerfile
        ports:
            - "8443:443"
            - "8080:80"
        networks:
            - transcendence-network
        environment:
            - XDG_CONFIG_HOME="/app/data"
        volumes:
            - caddy-volume:/data/caddy/
        develop:
            watch:
              - action: sync+exec
                path: ./caddy-service/
                target: /app
                ignore:
                    - .dockerfile
                    - Dockerfile
                exec:
                    command: "caddy reload"
        depends_on:
            frontend:
                condition: service_started
            database-service:
                condition: service_healthy
            # auth-service:
            #     condition: service_started
            # chat-service:
            #     condition: service_started
            # age-of-war-service:
            #     condition: service_started
            # file-management-service:
            #     condition: service_started
            # kong-service:
            #     condition: service_started
            # user-analytics-service:
            #     condition: service_started
            # user-management-service:
            #     condition: service_started
        restart: always
# ======================== CHAT ========================
    # chat-service:
    #     container_name: chat-service
    #     build:
    #         context: ./chat-service
    #         dockerfile: Dockerfile
    #         additional_contexts:
    #             shared_ressources: ./shared
    #     expose:
    #         - "3000" # arbitrary
    #     develop:
    #         watch:
    #             - path: ./chat-service
    #               action: sync
    #               target: /app
    #               ignore:
    #                 - .git
    #     networks:
    #         - transcendence-network
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #         # user-management-service:
    #         #     condition: service_started
    #         #     restart: true
    #         # tournament-service:
    #         #     condition: service_started
    #         #     restart: true
    #         # file-managment-service:
    #         #     condition: service_started
    #         #     restart: true
    #     restart: unless-stopped
# ======================== FRONT ========================
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
            additional_contexts: 
                shared_ressources: ./shared
        expose:
            - "3000"
        develop:
            watch:
                - path: ./frontend
                  action: sync
                  target: /app
                  ignore:
                    - .git
                    - .dockerignore
                #   exec:
                #     command: "./scripts/handle_file_change.sh {{ .Path }}"
                # - path: shared/scripts
                #   target: /app/scripts
                #   action: sync
        networks:
            - transcendence-network
        restart: unless-stopped
# # ======================== AUTHENTICATION ========================
    # auth-service:
    #     build:
    #         context: ./auth-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - 3001
    #     secrets:
    #         - api_pass
    #         - jwt_secret
    #         - github_oauth_id
    #         - github_oauth_secret
    #     develop:
    #         watch:
    #             - path: ./auth-service
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         user-management-service:
    #             condition: service-started
    #             restart: true
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #     restart: unless-stopped
# ======================== DB ========================
    database-service:
        container_name: database-service
        env_file: .env
        build:
            context: ./database-service
            dockerfile: Dockerfile
            additional_contexts: 
                shared_ressources: ./shared
        expose: 
            - "5000" # check if port is acceptable
        environment:
            DATABASE_URL: ${DATABASE_URL}
            DB_USER: "user"
            DB_PASS_FILE: /run/secrets/db_password
            LAUNCH_MODE: "dev"
        secrets:
            - db_password
            - api_pass
        develop:
            watch:
                - path: ./database-service
                  action: sync+exec
                  target: /app
                  exec:
                    command: "./scripts/handle_file_change.sh {{ .Path }}"
                - path: shared/scripts
                  target: /app/scripts
                  action: sync
        volumes:
            - ./db_data:/app/data # bind mount for now so that the db can be checked outside
        networks:
            - transcendence-network
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"] #Probably need to put https in future
            interval: 10s
            timeout: 30s
            retries: 5
            start_period: 5s
# # ======================== AGE OF WAR ========================
    # age-of-war-service:
    #     build:
    #         context: ./age-of-war-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - # #
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     restart: unless-stopped
# # ======================== FILE MANAGEMENT ========================
    # file-management-service:
    #     build:
    #         context: ./file-management-service
    #         dockerfile: Dockerfile
    #     expose: 
    #         - #
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #     restart: unless-stopped
# # ======================== KONG ========================
    # kong-service:
    #     build:
    #         context: ./kong-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - #
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     restart: unless-stopped
# # ======================== TOURNAMENT ========================
    # tournament-service:
    #     build:
    #         context: ./tournament-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - # 
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #         kong-service:
    #             condition: service_started
    #         age-of-war-service:
    #             condition: service_started
    #     restart: unless-stopped
# # ======================== USER ANALYTICS ========================
    # user-analytics-service:
    #     build:
    #         context: ./user-analytics-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - #
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #     restart: unless-stopped
# # ======================== USER MANAGEMENT ========================
    # user-management-service:
    #     build:
    #         context: ./user-management-service
    #         dockerfile: Dockerfile
    #     expose:
    #         - 3002
    #     secrets:
    #         - api_pass
    #     develop:
    #         watch:
    #             - path: ./**/*.tsx
    #               action: sync+exec
    #               target: /app
    #               exec:
    #                 command: "./scripts/handle_file_change.sh {{ .Path }}"
    #             - path: ../shared/scripts
    #               target: /app/scripts
    #               action: sync
    #     depends_on:
    #         database-service:
    #             condition: service_healthy
    #             restart: true
    #     restart: unless-stopped

volumes:
    caddy-volume: 

networks:
    transcendence-network:
        driver: bridge

secrets:
    github_oauth_id:
        file: secrets/github_oauth_id
    github_oauth_secret:
        file: secrets/github_oauth_secret
    api_pass:
        file: secrets/api_pass
    db_password:
        file: secrets/db_password
    jwt_secret:
        file: secrets/jwt_secret
    # db_url:
    #     environment: "DATABASE_URL" 